# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2007-2017
  project: Data Query
  version: 2.1
  release: 2.1.0
  latex_documents:
  - - Index
    - dataquery.tex
    - Data Query
    - Francois Suter
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    expressions:
    - http://docs.typo3.org/typo3cms/extensions/expressions/
    - null
    tesseract:
    - http://docs.typo3.org/typo3cms/extensions/tesseract/
    - null
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
...
